Create Hall_of_jail.md
LittleSkinCommspt/commspt-bot-manual pull request #16
Opened 2022-03-29 03:36 UTC by FLYEMOJ1

添加Hall of Jail.
用于记录违反TOS并被拒绝提供服务的用户。

2022-03-29 03:48 UTC, FLYEMOJ1 commented
尚未完成。
需讨论图片保存位置。

2022-03-29 04:14 UTC, jinzhijie requested changes
请参照中文排版指北修改此文档

2022-03-29 04:46 UTC, FLYEMOJ1 commented
> 请参照中文排版指北修改此文档

望能修改部分内容让我能理解去修改哪些部分。

2022-03-29 05:05 UTC, jinzhijie commented
@FLYEMOJ1 英文左右加空格

2022-03-29 05:44 UTC, FLYEMOJ1 commented
@jinzhijie 左右加空格不太美观

2022-03-29 06:36 UTC, FLYEMOJ1 commented
是我本人理解错误。
已做修改。

2022-03-29 07:55 UTC, FLYEMOJ1 commented
以LSCommspt-bot的image储存方式保存。
请注意命名。

2022-03-29 07:55 UTC, FLYEMOJ1 commented
@jinzhijie 检查提交信息，请（半恼

2022-03-31 03:50 UTC, Cubik65536 requested changes
根据标准命名文件并将图片文件放入 `assets` 或 `assets/images` 文件夹，像文件内加入图片。
------
其他看起来都没问题

2022-04-05 04:11 UTC, Cubik65536 requested changes
然后向文章内加入图片/图片链接？我觉得没别的问题了

2022-04-05 04:28 UTC, FLYEMOJ1 commented
已更新。
最近在忙别的计划，望诸位有时间可以帮我继续完善该文档。

2022-04-05 12:38 UTC, Mashirl approved these changes

2022-04-05 12:56 UTC, Cubik65536 approved these changes

2022-04-05 12:57 UTC, Qubik65536 commented
@Restent @jinzhijie

2022-04-05 13:26 UTC, jinzhijie requested changes
图片确实是上传了，但是文档里没写呀

2022-04-05 15:23 UTC, merged

2022-04-05 15:39 UTC, Cubik65536 commented
我会在 UTC 9:30 PM 左右提交新的 pull request

2022-04-07 03:52 UTC, Cubik65536 commented
#17 完成了剩下的工作