Updates on the documentation
LittleSkinCommspt/commspt-bot-manual pull request #5
Opened 2021-05-10 17:44 UTC by Cubik65536

- Update command.md and functions.md to match the actual functios of the bot.
- Remove non-reachable E-Mail address.

2021-05-10 21:33 UTC, jinzhijie requested changes

2021-05-10 21:33 UTC, jinzhijie commented on functions.md
>  <chat-message nickname="Alex" color="#cc0066">富强民主\<敏感词\>文明和谐</chat-message>
这两个还没有实装哦，你标注一下未实装

2021-05-11 12:37 UTC, Qubik65536 commented on functions.md
>  <chat-message nickname="Alex" color="#cc0066">富强民主\<敏感词\>文明和谐</chat-message>
> 这两个还没有实装哦，你标注一下未实装

Changed as requested

2021-05-11 21:38 UTC, jinzhijie approved these changes

2021-05-11 21:38 UTC, merged